import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ComingSoonButton } from "@/components/ComingSoonButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-gray-600 body-font border border-gray-200">
          <div className="flex flex-wrap p-2 md:p-4 flex-col md:flex-row items-center bg-[url('../public/OpenCalendar.svg')] bg-[left_-3em_top_120%] md:bg-[left_-2em_top_50%] bg-[length:15em] md:bg-[length:20em] bg-no-repeat">
            <h1>
              <a className="flex title-font font-bold items-center text-gray-900 mb-2">
                <span className="md:ml-3 text-2xl">OpenCalendar</span>
              </a>
            </h1>
            <nav className="md:ml-auto my-0 mr-7 text-base ">
              <ComingSoonButton>
                <ul className="flex flex-wrap space-x-7 font-bold">
                  <li className="">
                    <a href="" className="b hover:text-gray-900 py-2 px-1">
                      ログイン
                    </a>
                  </li>
                  <li className="">
                    <a href="" className="hover:text-gray-900 py-2 px-1">
                      設定
                    </a>
                  </li>
                </ul>
              </ComingSoonButton>
            </nav>
          </div>
        </header>
        {children}
        <footer className="bg-gray-50 h-2"></footer>
        {/* <footer className="bg-blue-400 text-center py-8">
          <p>copyright</p>
        </footer> */}
      </body>
    </html>
  );
}
